# Generated by Django 2.1.4 on 2018-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('camera_link', models.CharField(max_length=1000)),
                ('file_type', models.CharField(max_length=8)),
            ],
        ),
    ]
