# Generated by Django 2.1.4 on 2018-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
